config/routes.rb
PineappleRepairs::Application.routes.draw do

  devise_for :contractors, :controllers => { :registrations => "registrations"}

  # resources :problem, only: [:new, :edit, :create, :update]
  # resources :models, only: [:new, :edit, :create, :update]
  # resources :devices, only: [:new, :edit, :create, :update, :index]
  # resources :networks, only: [:new, :edit, :create, :update]

  resources :jobs, only: [:new, :create] do
    collection do
      # stop 404 in wizard
      get '' => :create
      get :unavailable, to: "jobs#unavailable"
    end
  end

  authenticated :contractor do
    resources :jobs, only: [:index, :show]

    resources :contractors do
      member do
        post :verify, to: "contractors#verify"
      end

      resources :jobs, only: [] do
        member do
          post :accept, to: "jobs#accept"
          post :finish, to: "jobs#finish"
        end

        collection do
          get :current, to: "jobs#current"
          get :finished, to: "jobs#finished"
          get :available, to: "jobs#available"
        end
      end
    end
  end

  get "/after",         to: "pages#after_sign_up"
  get "/contact",       to: "pages#contact"
  get "/about",         to: "pages#about"
  get "/repairs",       to: "devices#index"
  get "/diy",           to: "pages#diy"

  root 'pages#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Wizard

  belongs_to :device
  belongs_to :model
  belongs_to :problem
  belongs_to :network
  belongs_to :location
  belongs_to :contractor

  first_step  = lambda { |r| r.current_step == r.steps[0] }
  second_step = lambda { |r| r.current_step == r.steps[1] }
  third_step  = lambda { |r| r.current_step == r.steps[2] }
  fourth_step = lambda { |r| r.current_step == r.steps[3] }
  fifth_step  = lambda { |r| r.current_step == r.steps[4] }
  sixth_step  = lambda { |r| r.current_step == r.steps[5] }

  # first step validation
  validates :device_id, presence: true, if: second_step

  # second step validation
  validates :model_id, presence: true, if: third_step

  # third step validation
  validates :network_id, presence: true, if: fourth_step

  # fourth step validation
  validates :problem_id, presence: true, if: fifth_step

  # fourth step validation
  validates :location_id, presence: true, if: first_step

  # fifth step validations
  validates :name, length: {in: 1..40 },  presence: true, if: sixth_step
  validates :email, length: {in: 1..100 },  presence: true, if: sixth_step
  validates :phone_number, length: {in: 7..20 }, presence: true, if: sixth_step

  scope :available, -> { where(contractor_id: nil) }

  def steps
    %w[ location device model network problem contact ]
  end

  def data_for_step id=nil
    if current_step == "device"
      Device.all
    elsif current_step == "model"
      Model.where(device_id: id)
    elsif current_step == "network"
      Network.all
    elsif current_step == "problem"
      Problem.all
    else
      []
    end
  end

  def pretty_phone_number
    pretty_phone_number = "(#{phone_number[0,3]}) #{phone_number[3,3]}-#{phone_number[6,10]}"
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :redirect_if_not_authenticated, except: [:new, :create, :unavailable]
  before_filter :redirect_if_not_verified, except: [:new, :create, :unavailable]

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    @data = Device.all
  end

  def index
  end

  def create
    @job = create_job_from_cookie

    assign_params @job

    @job.next_state params[:back]

    if @job.current_step == "device" && @job.device_id.present? && !params[:back]
      @job.next_state params[:back]
    end

    @data = @job.data_for_step @job.device_id

    if !@job.new_record?
      cookies.delete(:job)

      UserMailer.job("created", "customer", @job)
      UserMailer.job("created", "contractor", @job)

      redirect_to root_path, notice: "Job Successfully Created - Our technicians will be in touch soon"
    elsif @job.current_step == "location" && @job.location.nil? && params[:job].present?
      cookies.delete(:job)
      redirect_to unavailable_jobs_path
    else
      cookies[:job] = YAML::dump @job.attributes.merge( "current_step" => @job.current_step )
      render :new
    end
  end

  def unavailable
  end

  def accept
    @job = Job.find(params[:id])
    @job.contractor = Contractor.find(params[:contractor_id])
    @job.save

    UserMailer.job("accepted", "customer", @job)

    redirect_to contractor_path(params[:contractor_id])
  end

  def finish
    @job = Job.find(params[:id])

    UserMailer.job("closed", "customer", @job)

    if @job.contractor == current_contractor
      @job.finished = true
      @job.save
    end

    redirect_to contractor_path(params[:contractor_id])
  end

  def current
    @jobs = current_contractor.unfinished_jobs

    @title = "current"

    render "job_list"
  end

  def finished
    @jobs = current_contractor.finished_jobs

    @title = "finished"

    render "job_list"
  end

  def available
    @jobs = Job.available.where(location: current_contractor.location)

    @title = "available"

    render "job_list"
  end

private

  def create_job_from_cookie
    if params[:restart]
      cookies.delete(:job)
    end

    cookies[:job].present? ? Job.new( YAML::load( cookies[:job] ) ) : Job.new
  end

  def assign_params job
    case job.current_step
    when "device"
      job.device_id = params[:device_id]
    when "model"
      job.model_id = params[:model_id]
    when "network"
      job.network_id = params[:network_id]
    when "problem"
      job.problem_id = params[:problem_id]
    when "location"
      if params[:device_id].present?
        job.device_id = params[:device_id]
      end

      if params[:job] && params[:job][:location].present?
        location = Location.where( city: params[:job][:location][:city].downcase )

        if ( params[:job][:location][:country].present? )
          location.where( country: params[:job][:location][:country].downcase )
        end

        job.location = location.first
      end
    when "contact"
      if params[:job]
        job.name = params[:job][:name]
        job.email = params[:job][:email]
        job.phone_number = params[:job][:phone_number]
      end
    else
      raise "should never end up here"
    end
  end
end

app/views/jobs/_contact_step.html.erb
<div class="normal-form">
	<div class="form-row">
		<%= f.text_field :name, placeholder: "Name" %>
	</div>
	<div class="form-row">
		<%= f.text_field :email, placeholder: "Email" %>
	</div>
	<div class="form-row">
		<%= f.text_field :phone_number, placeholder: "Phone Number" %>
	</div>
	<div class="button-row">
		<%= f.submit :"Get In Touch!", class: "btn btn-primary" %>
	</div>
</div>

app/views/jobs/_device_step.html.erb
<% @data.each do |device| %>
  <div class="col-sm-3 col-xs-6 col-xs-offset-3 col-sm-offset-0 text-center text-center job-choice">

    <%= f.button name: "device_id", value: device.id, class: "" do %>
    	<span class="btn btn-primary"><%= device.name %></span>
    <% end %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div class="col-sm-12">
  <div class="meta">
    <div class="job-meta-section page-section">
      <header class="blue-header">
        <h3 class="heading">Contact Info</h3>
      </header>
        <ul>
          <li><%= job.name %></li>
          <li><a href="mailto:<%= job.email %>" target="_blank"><%= job.email %></a></li>
          <li><%= job.pretty_phone_number %></li>
          <li><%= job.location.city.capitalize %>, <%= job.location.country.capitalize %></li>
        </ul>
    </div>

    <div class="job-meta-section page-section">
      <header class="blue-header">
        <h3 class="heading">Job Details</h3>
      </header>
        <ul>
        <li><%= job.problem.name %></li>
        <li><%= job.model.name %></li>
        <li><%= job.network.name %></li>
        <li>Created: <%= job.created_at.to_formatted_s(:long_ordinal) %></li>

      </ul>
    </div>

  </div>
</div>

<div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4 col-md-2 col-md-offset-5">

  <% if job.contractor.nil? %>
    <%= form_tag accept_contractor_job_path(current_contractor, job), class: 'form validate', html: {role: 'form'} do %>
        <div class="form-group">
          <%= submit_tag 'Take Job', class: 'btn btn-primary inputbtn transition' %>
        </div>
      <% end %>
  <% elsif current_contractor.can_close?(job) %>
    <%= form_tag finish_contractor_job_path(current_contractor, job), class: 'form validate', html: {role: 'form'} do %>
        <div class="form-group">
          <%= submit_tag 'Close Job', class: 'btn btn-primary inputbtn transition' %>
        </div>
      <% end %>
  <% end %>
</div>

app/views/jobs/_job_list_item.html.erb
<div class="job-list-item <% if half %>col-md-6 col-sm-6<% else %>col-md-3 col-sm-4<% end %> col-xs-12">

  <%= link_to job_path(job_list_item) do %>
    <%= image_tag("devices/#{job_list_item.model.name.downcase}.png") %>
    <div class="job-list-item-meta">
        <p class="job-list-item-name"><%= job_list_item.model.name %></p>


        <p class="job-list-item-problem"><%= job_list_item.problem.name %></p>
        <p class="job-list-item-city"><%= job_list_item.location.city.capitalize %></p>
    </div>
  <%end%>

  <div class="job-list-item-button">
    <% if job_list_item.contractor.nil? %>
      <%= form_tag accept_contractor_job_path(current_contractor, job_list_item), class: 'form validate', html: {role: 'form'} do %>
        <div class="form-group">
          <%= submit_tag 'Take Job', class: 'btn btn-primary inputbtn transition' %>
        </div>
      <% end %>
    <% elsif !job_list_item.finished && job_list_item.contractor == current_contractor %>
      <%= form_tag finish_contractor_job_path(current_contractor, job_list_item), class: 'form validate', html: {role: 'form'} do %>
        <div class="form-group">
          <%= submit_tag 'Close Job', class: 'btn btn-primary inputbtn transition' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/jobs/_location_step.html.erb
<div class="normal-form location-form">
	<div class="form-row">
		<%= text_field_tag "", nil, class: 'autocomplete' %>

		<%= f.fields_for :location do |location| %>
		  <%= location.hidden_field :city,  class: 'city-field' %>
		  <%= location.hidden_field :country, class: 'country-field' %>
		<% end %>
	</div>


	<div class="button-row">
		<%= f.submit "submit", class: "btn btn-primary" %>
	</div>
</div>

app/views/jobs/_model_step.html.erb
<% @data.each do |device| %>
  <div class="col-sm-3 col-xs-6 col-xs-offset-3 col-sm-offset-0 text-center text-center job-choice">

    <%= f.button name: "model_id", value: device.id, class: "" do %>
    	<%= image_tag "devices/#{device.name.downcase}.png" %>
    	<span class="btn btn-primary"><%= device.name %></span>
    <% end %>
  </div>
<% end %>

app/views/jobs/_more_options.html.erb
<div class="inner-section">
  <div class="section-page-landing section-grey">
    <div class="inner-section">
      <div class="container">
        <h2 class="text-center">More Options?</h2>
        <div class="row">
          <div class="col-md-12 text-center option">
            <h3>DIY Kits</h3>

            <h4>
              If you're tech savy and want to try your hand at fixing your own phone check out our selection of kits
            </h4>

            <%= link_to "Learn More", diy_path %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_network_step.html.erb
<% @data.each do |network| %>
  <div class="col-sm-3 col-xs-6 col-xs-offset-3 col-sm-offset-0 text-center job-choice">

    <%= f.button name: "network_id", value: network.id, class: "" do %>
    	<span class="btn btn-primary"><%= network.name %></span>
    <% end %>
  </div>
<% end %>

app/views/jobs/_problem_step.html.erb
<% @data.each do |problem| %>
  <div class="col-sm-3 col-xs-6 col-xs-offset-3 col-sm-offset-0 text-center text-center job-choice">

    <%= f.button name: "problem_id", value: problem.id, class: "" do %>
    	<%= image_tag "problems/#{problem.name.downcase}.png" %>
    	<span class="btn btn-primary"><%= problem.name %></span>
    <% end %>
  </div>
<% end %>

app/views/jobs/job_list.html.erb
<%= render partial: '/shared/banner', locals: { title: 'Jobs'} %>

<%= render "contractors/subnav" %>

<div class="section-page-landing section-grey">
  <div class="inner-section">

    <div class="container">
    	<div class="row product-row">
    		<div class="col-xs-12">
    			<div class="jobs page-section">
	    			<header class="blue-header">
				    	<h2><%= @title.capitalize %> Jobs</h2>
				    </header>

			      <div class="job-list-items section-body">
				      <% if @jobs.length > 0 %>
				      	<%= render partial: "job_list_item", collection: @jobs, locals: { half: false } %>
				      <% else %>
				      	<h3>
				      		No <%= @title %> jobs to show.
				      	</h3>
				      <% end %>
				    </div>
		    	</div>
		    </div> <!-- .col-xs-12 -->
	    </div>
	  </div> <!-- .container -->
  </div> <!-- .inner-section -->
</div> <!-- .section-page-landing -->

app/views/jobs/new.html.erb
<div class="section-page-landing">
  <div class="inner-section jobs-new">
    <div class="container">
      <div class="row">
        <hr class="divider"/>
        <div class="job-progress">
          <% @job.steps.each_with_index do |step, i| %>
            <% current_step_index = @job.steps.index(@job.current_step).to_i %>
            <% if step == @job.current_step %>
              <div class="col-sm-2">
                <h4 class="shown progress-title">
                  <span class="step-name"><%= "#{i+1}. #{step.upcase}" %></span>
                  <i class="fa fa-caret-right carat"></i>
                </h4>
              </div>
            <% else %>
              <div class="col-sm-2">
                <h4 class="progress-title text-primary <% if i == (current_step_index - 1) || i == (current_step_index + 1) %>shown<% end %>">
                  <span class="step-name"><%= "#{i+1}. #{step.upcase}" %></span>
                  <i class="fa fa-caret-right carat"></i>
                </h4>
              </div>
            <% end %>
          <% end %>
        </div>
        <hr class="divider"/>

        <div class="row job-choices">
          <%= form_for Job.new do |f| %>
            <%= render "/jobs/#{@job.current_step}_step", f: f, job: @job %>

            <% unless @job.first_step? %>
              <div class="change-steps">
                <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3">
                  <%= f.button :back, name: "back", value: "true", class: "btn btn-default" %>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3"><%= f.button :restart, name: "restart", value: "true", class: "btn btn-default" %></div>
              </div>
            <% end %>

          <% end %>

        </div>
      </div>
    </div> <!-- .container -->
  </div>
</div>

<%= render "/jobs/more_options" %>

<% if @job.current_step == "location" %>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<% end %>

app/views/jobs/show.html.erb
<div class="body-content">
	<div class="section-page-landing section-grey">
	  <div class="inner-section">
	    <div class="container">
	    	<div class="row job">
	      <%= render @job %>
	    	</div>
	    </div>
	  </div>
	</div>
</div>

app/views/jobs/unavailable.html.erb
<%= render partial: '/shared/banner', locals: { title: "We Aren't In Your Area!"} %>
<div class="section-page-landing">
  <div class="inner-section">
    <div class="container">
      <h2 class="text-center">Sorry About That!</h2>
      <p>
        We're working hard to get all over North America but haven't gotten into your location yet.
      </p>
    </div>
  </div>
</div>