config/routes.rb
PineappleRepairs::Application.routes.draw do

  devise_for :contractors, :controllers => { :registrations => "registrations"}

  # resources :problem, only: [:new, :edit, :create, :update]
  # resources :models, only: [:new, :edit, :create, :update]
  # resources :devices, only: [:new, :edit, :create, :update, :index]
  # resources :networks, only: [:new, :edit, :create, :update]

  resources :jobs, only: [:new, :create] do
    collection do
      # stop 404 in wizard
      get '' => :create
      get :unavailable, to: "jobs#unavailable"
    end
  end

  authenticated :contractor do
    resources :jobs, only: [:index, :show]

    resources :contractors do
      member do
        post :verify, to: "contractors#verify"
      end

      resources :jobs, only: [] do
        member do
          post :accept, to: "jobs#accept"
          post :finish, to: "jobs#finish"
        end

        collection do
          get :current, to: "jobs#current"
          get :finished, to: "jobs#finished"
          get :available, to: "jobs#available"
        end
      end
    end
  end

  get "/after",         to: "pages#after_sign_up"
  get "/contact",       to: "pages#contact"
  get "/about",         to: "pages#about"
  get "/repairs",       to: "devices#index"
  get "/diy",           to: "pages#diy"

  root 'pages#index'
end

app/views/shared/_back_to_top.html.erb
<!-- BACK TO TOP BUTTON -->
<div id="back-top">
	<%= link_to "#top" do %>
  	<i class="fa fa-chevron-up"></i>
  <% end %>
</div>
<!-- END BACK TO TOP -->

app/views/shared/_banner.html.erb
<div class="banner">
  <div id="banner" class="slogan">
    <h2 class="text-center">
      <%= title %>
    </h2>
  </div>
</div>

app/views/shared/_banner_homepage.html.erb
<div class="banner homepage">

  <div id="banner" class="awesome-slogan container">
    <h2>
      Don't Pine Over <br/> Your <span>Apple</span> Products
    </h2>
    <h4>
      A Technician will meet you at a location of <br/>
      your choice to repair your apple and non apple devices
    </h4>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row text-center">
      <div class="col-sm-4">
        <h5>Company</h5>
        <%= link_to "About Us", about_path %><br/>
        <% if current_contractor.nil? %>
            <%= link_to "Technical Login", contractor_session_path %><br/>
            <%= link_to "We're Hiring", new_contractor_registration_path %><br/>
        <% else %>
            <%= link_to "Available Jobs", contractor_path(current_contractor) %><br/>
            <%= link_to destroy_contractor_session_path, method: :delete do %>
              Logout
            <% end %><br/>
        <% end %>
      </div>
      <div class="col-sm-4">
        <h5>Store Hours</h5>
        <p>
          Mon - Fri 11am - 6pm<br />
          Saturday  11am - 4pm<br />
          Sunday    Closed
        </p>
      </div>
      <div class="col-sm-4">
        <h5>Store Location</h5>
        <address>
          <strong>Pineapple Repairs</strong><br>
          Waterfront Station<br>
          25-601 West Cordova Street<br>
          Vancouver, BC, Canada<br>
          Toll Free: 1 (888) 5 REPAIR<br>
          Main Line: 778 889 7642<br>
          <a href="mailto:pineapplerepairs@gmail.com">PineappleRepairs@gmail.com</a>
        </address>
      </div>
    </div>
    <div class="copyright row">
      <div class="col-xs-12">
        &copy; 2011 - <%= Time.now().year %> <%= link_to "Pineapple Repairs", root_path %>
      </div>
    </div>
  </div>
</footer>
<!-- END FOOTER -->

app/views/shared/_menu.html.erb
<div id="nav-menu">
  <div id="logo">
    <a href="/">
      <%= image_tag("logo-matt.png") %>
    </a>
  </div>
  <div class="row">


    <div class="col-xs-9 col-xs-offset-3">

      <!-- NAV MENU -->
      <div class="menus" id="myScrollspy">
        <nav class="navbar" role="navigation">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            <span class="icon-oxp-nav"></span>
          </button>

          <div id="bs-navbar-collapse-1" class="collapse navbar-collapse">
            <ul class="list-inline nav navbar-nav">
             <!-- <%= nav_link("Home", root_path) %>-->


              <%= nav_link("Repairs", repairs_path) %>
              <%= nav_link("About Us", about_path) %>

              <% if contractor_signed_in? %>
                <%= nav_link("Account", contractor_path(current_contractor)) %>
                <li>
                  <%= link_to destroy_contractor_session_path, method: :delete do %>
                    Logout
                  <% end %>
                </li>
              <% else %>
                <%= nav_link("On Demand", jobs_path(restart: true)) %>
                <%= nav_link("We're Hiring!", new_contractor_registration_path) %>
              <% end %>
            </ul>
          </div>
        </nav>

      </div>

    </div>

  </div>

</div>