config/routes.rb
PineappleRepairs::Application.routes.draw do

  devise_for :contractors, :controllers => { :registrations => "registrations"}

  # resources :problem, only: [:new, :edit, :create, :update]
  # resources :models, only: [:new, :edit, :create, :update]
  # resources :devices, only: [:new, :edit, :create, :update, :index]
  # resources :networks, only: [:new, :edit, :create, :update]

  resources :jobs, only: [:new, :create] do
    collection do
      # stop 404 in wizard
      get '' => :create
      get :unavailable, to: "jobs#unavailable"
    end
  end

  authenticated :contractor do
    resources :jobs, only: [:index, :show]

    resources :contractors do
      member do
        post :verify, to: "contractors#verify"
      end

      resources :jobs, only: [] do
        member do
          post :accept, to: "jobs#accept"
          post :finish, to: "jobs#finish"
        end

        collection do
          get :current, to: "jobs#current"
          get :finished, to: "jobs#finished"
          get :available, to: "jobs#available"
        end
      end
    end
  end

  get "/after",         to: "pages#after_sign_up"
  get "/contact",       to: "pages#contact"
  get "/about",         to: "pages#about"
  get "/repairs",       to: "devices#index"
  get "/diy",           to: "pages#diy"

  root 'pages#index'
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include Gravtastic
  gravtastic

  has_many :jobs
  belongs_to :location

  validates :phone_number, presence: true
  validates :name, presence: true
  validates :location_id, presence: true

  def unfinished_jobs
    jobs.where(finished: false).where(location: location)
  end

  def finished_jobs
    jobs.where(finished: true).where(location: location)
  end

  def can_close? job
    job.contractor == self && !job.finished
  end

  def pretty_phone_number
    "(#{phone_number[0,3]}) #{phone_number[3,3]}-#{phone_number[6,10]}" if phone_number.present?
  end
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_filter :redirect_if_not_authenticated
  before_filter :redirect_if_not_verified, except: [:verify]
  before_filter :redirect_if_not_admin, only: [:index]

  def index
    @contractors = Contractor.all
  end

	def show
    @contractor = Contractor.find(params[:id])
		@jobs_finished = current_contractor.finished_jobs
		@jobs_current = current_contractor.unfinished_jobs
	end

  def verify
    @contractor = Contractor.find(params[:id])
    @contractor.verified = true
    @contractor.save

    redirect_to contractors_path, notice: "Contractor Successfully Verified"
  end

end

app/views/contractors/_contractor.html.erb
<div class="col-sm-4">
	<%= link_to contractor do %>
	<h3><%= contractor.name %></h3>
	<% end %>
	<p><a href="mailto:<%= contractor.email %>" target="_blank"><%= contractor.email %></a></p>
	<% if contractor.phone_number %>
		<p><%= contractor.pretty_phone_number %></p>
		<% end %>

	<% unless contractor.verified %>
	  <%= form_tag verify_contractor_path(contractor), class: 'form validate', html: {role: 'form'} do %>
	    <div class="form-group">
	      <%= submit_tag 'Verify', class: 'btn btn-primary inputbtn transition' %>
	    </div>
	  <% end %>
	<% else %>
		<p>Verified</p>

	<% end %>

</div>

app/views/contractors/_subnav.html.erb
<nav class="sub-nav">
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12 col-xs-offset-0">
      <ul class="list-inline">
        <li><%= link_to "Available", available_contractor_jobs_path(current_contractor) %></li>
        <li><%= link_to "Current", current_contractor_jobs_path(current_contractor) %></li>
        <li><%= link_to "Finished", finished_contractor_jobs_path(current_contractor) %></li>
        <li><%= link_to "Contractors", contractors_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/contractors/index.html.erb
<%= render partial: '/shared/banner', locals: { title: 'Contractors'} %>

<div class="section-page-landing section-grey">
	<%= render "contractors/subnav" %>
	<div class="inner-section">
		<div class="container">
  		<div class="row product-row">
	    	<div class="col-xs-12">
	    		<div class="contractors page-section">
		  		<header class="blue-header">
			    	<h2>Contractors</h2>
			    </header>

	    		<div class="section-body">
		    		<%= render @contractors %>
		    	</div>
		    </div>
	    	</div>

		  </div>
	  </div>
  </div>
</div>

app/views/contractors/show.html.erb
<%= render partial: '/shared/banner', locals: { title: 'Contractors'} %>

<div class="section-page-landing section-grey">

	<%= render "contractors/subnav" %>
	<div class="inner-section">

		<div class="container">

			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<div class="page-section">
						<header class="blue-header">
							<h3>Account Info</h3>
						</header>
						<div class="account-box">
							<div class="account-image">
								<%= image_tag(@contractor.gravatar_url) %>
							</div>

							<div class="account-meta">
								<ul>

									<li>
										<%= @contractor.name %>
									</li>
									<li>
										<%= @contractor.email %>
									</li>
									<li>
										<%= @contractor.pretty_phone_number %>
									</li>
									<% if @contractor.location %>
									<li>

										<%= @contractor.location.city.capitalize %>, <%= @contractor.location.country.capitalize %>
									</li>
									<% end %>
								</ul>
							</div>
						</div>
					</div> <!-- .page-section -->

				</div>


			</div>

			<div class="container">
				<h2>Your Jobs</h2>
			</div>
			<div class="row">
				<div class="jobs-current col-sm-6">
					<div class="page-section">
						<header class="blue-header">
							<h3>Current Jobs</h3>
						</header>
						<div class="section-body">
							<%= render partial: "jobs/job_list_item", collection: @jobs_current, locals: { half: true } %>
						</div>
					</div>
				</div>
				<!-- <div class="jobs-available col-sm-6">
					<div class="page-section">
						<header class="blue-header">
							<h3>Available Jobs</h3>
						</header>
						<div class="section-body">
							<%= render partial: "jobs/job_list_item", collection: @jobs_available, locals: { half: true } %>
						</div>

					</div>
				</div> -->

				<div class="jobs-finished col-sm-6">
					<div class="page-section">
						<header class="blue-header">
							<h3>Finished Jobs</h3>
						</header>
						<div class="section-body">
							<%= render partial: "jobs/job_list_item", collection: @jobs_finished, locals: { half: true } %>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- .container -->
	</div> <!-- .inner-section -->
</div>